[project]
name = "dbs-ai-chatbot-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.9.4",
    "chromadb>=1.1.1",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.6",
    "langchain-mistralai>=1.1.1",
    "langwatch>=0.8.0",
    "mistralai>=1.9.11",
    "python-dotenv>=1.1.1",
]
